---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBLMITx7Z+hWFCNHOxqpdQ5TmRds7bDV5mOOIw1dqhQrJEptz/6idHwPQe5ZQ2WGwCihsg6gbYtPPe1Dbi/o7VGxWdjvJ4IsQl1TbKaAi6vRP26AWfCc8wDxzFEJe8rjpj7ROIOiWD6CzOrSjbNgFVDSj3xyMhRyZYng5cvdWxePzHM5WvAGoEmWfno8kwwRZKakY05/+iSHHowq+6hwit+MaRaAGllGtooXFZj6rkIvOVqgsyc7jrM1GI9JFhLN8mnCp5eDFAHxfmSk1C5+YwnB8xvp115uNiTTUCEJJBj8oYd4uGaE8G79OKdw/BvA7ZCxdK20yxWqHs9R6yfcP3BoTEB0D4kX8+ulqOHEnzvR7Lv6R9K/U41oGXIbmLSVF5jx8yaldZaUUnOe1SIrYzgoaaHeXqwfn3cLMZYbB4h81r+ypnMYc9SzgixClYX7VfurCD+U5Av8UUTJPSDijqAFmFmBdNbbpifMJalFmlAQ6MJMcF+hAr1uOxvjaDuINijCPtLEqUflmLASiW26cpTRpqiwT6TsSxzR5y4msjBywgRz/yVDyOtm0twWcEDBvLOtOdb0TnFTUVe8tw6X8Umz3DazcrIoybDfE1zq7N3JkcIq37OyyX105FhAr5EuitFgXmo2lPF/gDD1aSqD/ajmMNtOP80fPsXzLxvy/1HNidsK4qhhgPrwYLOYsHxt7147vO55ICRi37PNJGS9SEXvsbR+DQc2QQQK7zxDHpxpqvSxOin4nYbAsgmUhi3GMFD4W+Izh1+7fmVvsmmbWJCHLVE5ugupvUE745MpqkaFklF5nkEKFfWcKFinVwVlnIWdBnhJiPDz2abqCwn+69Q38tWOWwsRG3yiNNqtV59ztGO8zqtlyv19XAQ9RKvKAEo87NloD0mNILD/WcDDf+EtImSbBGAajAPJXqO5+Vj
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
