---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBjuUAZ1PR6GqLZO5XYkTUprEYCGgdlZUPPcgGY+Ly8ZO8HCnAr3mbCIdhDL9LUJrhfxGdQ94YdOyqBD+yl+scFJoQnX3wNXzJ3rmRygfr7I4VFrPuiNGwAqgLce9jXSriMIU1c6E5VqqRTRs0jBCyb/HKpVwlxf2uWlKAmRELvygNp6pX46xpzpNxVWO91evvajr0UgVQk7erS+zvfC58MOp/XOMmnok2ls5lot/siHIMmzQ8H4PnbGKHqaTdLiw5ag+/VNY8MTZ7j9iexrEQRxZLHn5ivbqso7dmzlZfmyyA7RfeZxlU0Y/PvIw/RrqOJ+IxZF+MobMd/zbLZuQ7SJTpsYprL3mp2QbbIMNJA5VaiHxTRVK6y7TNEnhiCucwl62ztniuVJy21n1YZlrnGneWQRwA8fugwSGmsDhiyDCFKKA1XRUjsCTY0y4jpulQl4lePgSxU6GtCKx9l9sKwnL3QfKLQYTqFHqXIq2LRe/3dFqxNySIUp7Je58SQPUcrHNu5tDemU3YWwZc+1Ud6sbM/wL3IHbs8AsYZEqaGB0ZLzW1W3Y13dtUkx7G36mZNBaGtBc3muCORRaZyBl/kGiaP7F1dYQr6dTeKlcBqNxa4YJmt02+NGIvrOtlyzJQ47/ehWZFtqiOAQUTxnhPinwnr95xhqGZ8y4SaO6Og8+1nahg8xXwyhc524n0Z9K5RGU5iN7bPmn6SWvpV5MPGnZTB42+WS04j5F7wsw3pjunGSpbZ8ZOpWwWWtCdQ6nu70pO2GFp7zRUgfc0ZrMZSdKCPeuQISWYhMDT9qu5W+E+XHIZxTN0nZolpo1cgXh/94mRmlWOrcrmh+VNuO5kxVWn0JNzxVjxkuhzRMgyYioGyOmK37P+ELyU8WAYlT2CQy0eruioVUIs/4mh2tQ8R5H9Qs//yviMqZANUwCQo
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
