---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgC8hyaSPH2MGZxgi7AFLFjLJSz6FDQ3JOfjo18x6Uns8B0lsM+eECw0t7rxImu13xdFos3dwMgXtuqKMWNa4PMMnRGiupF1s5mrVbpqeatGaLZupHvfFM9kP1p8naQwgyrcRWaiBZIESIVEQeOr8Rj43k1oHmcBn7o+8jLyJP2upa4TLn+6zJyWG1DFlu5ciWZqyVwHgCmud17sCArCh/Ib4dS4FAXNdyizvcQUkhq/Hu/vz6G9zs9Bc+yz0ZvdmoJqapL97iC21ng3ou580nSL2hzsy6pK3vwK3tdVBW83VxszulqTKuxYJkuUG3tVoC6HYej7yZC5aNMw7MysiA9Gz4ivfXKM0VL3DaNJpmPw0rVkrCjjYX3/qn3W//3Imh4Lhe8P2dvYnaBlPLIxEQoxhlDlrj/WgQMTdrg/MFzqTRoK6zy3hIHQhVuJetFU+Fsdh7BbmNeQJ5Osawy4J5eKuiGFeGrFlMlWUG0pUkxnDV9d0eFdYwSOqMpW87b1+tlAP6i8xuZVhzXNEPcMWAFZHub9aH917G7+bNmfjtm07dXGRf4pQ78A+HzxF7waXJ2MupheEHhmDhFl88APIZq5SwuvKQtcgYOzSiOJ221KjvYPed2XXnq4HWQfKunDNEkUQhs5VJh00VCZfXJxAQdxwZPp5CYvSXG6MS4EJtFxXFUeCMH9wZQJDUEI/gf9ivW4G5fIiV4PQgIRTAmPo+4mArHepJN9Mblu5isJxZJAMZzlQVt5k0jpPC8W19R/UItxpLHmV/mF+7JqVUW6khdfV/m0eO4Ea6OTIblp/l2+2Aslogx/z4kpjVCJ85SjelF7IqBZu9lDpxX+19XDDPcdOv1ndDpvJXyQ8FHxIiW7mCGXgaCg1uwBPNBDdQx7LCgBKoVed9ZorkV6ctdqRtMWl5KCfk33gJa7VwVlqSFI
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
